name: Build Image

on:
  workflow_call:
    secrets:
      UCLOUD_HUB:
        required: true
      UCLOUD_USER:
        required: true
      UCLOUD_PASS:
        required: true
    inputs:
      artifact_name:
        required: true
        type: string
      ghcr_slug:
        required: true
        type: string
      uhub_slug:
        required: true
        type: string
    outputs:
      version:
        description: "Image tag from docker/metadata-action"
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    runs-on: self-hosted

    outputs:
      version: ${{ steps.meta.outputs.version }}

    steps:
    - uses: actions/checkout@v2

    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.artifact_name }}

    - name: Unzip artifact
      run: tar -xvf artifact.tar

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%y%m%d%H%M%S')"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to UCloud UHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.UCLOUD_HUB }}
        username: ${{ secrets.UCLOUD_USER }}
        password: ${{ secrets.UCLOUD_PASS }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ inputs.uhub_slug }}
          ${{ inputs.ghcr_slug }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha,prefix=${{ steps.date.outputs.date }}-

    - name: Build and push images
      uses: docker/bake-action@v1
      with:
        files: |
          ./docker-bake.hcl
          ${{ steps.meta.outputs.bake-file }}
        targets: build-all
        push: ${{ github.event_name != 'pull_request' }}
        set: |
          *.cache-from=type=registry,ref=${{ inputs.ghcr_slug }}:buildcache
          *.cache-to=type=registry,ref=${{ inputs.ghcr_slug }}:buildcache,mode=max
