name: Build Image

on:
  workflow_call:
    secrets:
      DOCKER_USER:
        required: false
      DOCKER_PASS:
        required: false
      ACR_USER:
        required: false
      ACR_PASS:
        required: false
      UCLOUD_USER:
        required: false
      UCLOUD_PASS:
        required: false
    inputs:
      artifact_name:
        description: 'Artifact to download and unpack before building image'
        required: false
        type: string
      ghcr_slug:
        description: 'Default GitHub Container Registry'
        required: true
        type: string
      hub_slug:
        description: 'Docker Hub, leave empty to skip pushing image to this registry'
        required: false
        type: string
      acr_slug:
        description: 'Aliyun Container Registry, leave empty to skip pushing image to this registry'
        required: false
        type: string
      uhub_slug:
        description: 'UCloud UHub, leave empty to skip pushing image to this registry'
        required: false
        type: string
    outputs:
      version:
        description: "Image tag from docker/metadata-action"
        value: ${{ jobs.build-image.outputs.version }}

jobs:
  build-image:
    runs-on: self-hosted

    outputs:
      version: ${{ steps.meta.outputs.version }}

    steps:
    - uses: actions/checkout@v2

    - name: Download a single artifact
      uses: actions/download-artifact@v2
      if: ${{ inputs.artifact_name }}
      with:
        name: ${{ inputs.artifact_name }}

    - name: Unzip artifact
      if: ${{ inputs.artifact_name }}
      run: tar -xvf artifact.tar

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%y%m%d%H%M%S')"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      if: ${{ github.event_name != 'pull_request' && inputs.hub_slug }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Login to UCloud UHub
      if: ${{ github.event_name != 'pull_request' && inputs.uhub_slug }}
      uses: docker/login-action@v1
      with:
        registry: uhub.service.ucloud.cn
        username: ${{ secrets.UCLOUD_USER }}
        password: ${{ secrets.UCLOUD_PASS }}

    - name: Login to Aliyun Container Registry
      if: ${{ github.event_name != 'pull_request' && inputs.acr_slug }}
      uses: docker/login-action@v1
      with:
        registry: registry.cn-beijing.aliyuncs.com
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_PASS }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ inputs.acr_slug }}
          ${{ inputs.uhub_slug }}
          ${{ inputs.ghcr_slug }}
          ${{ inputs.hub_slug }}
        tags: |
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
          type=semver,pattern=v{{major}}
          type=sha,prefix=${{ steps.date.outputs.date }}-

    - name: Build and push images
      uses: docker/bake-action@v1
      with:
        files: |
          ./docker-bake.hcl
          ${{ steps.meta.outputs.bake-file }}
        targets: build-all
        push: ${{ github.event_name != 'pull_request' }}
        set: |
          *.cache-from=type=registry,ref=${{ inputs.ghcr_slug }}:buildcache
          *.cache-to=type=registry,ref=${{ inputs.ghcr_slug }}:buildcache,mode=max

    - name: Check manifest
      if: github.event_name != 'pull_request'
      run: |
        docker buildx imagetools inspect ${{ inputs.ghcr_slug }}:${{ steps.meta.outputs.version }}

    # May slow down workflow process. Disabled by default
    # - name: Inspect image
    #   if: github.event_name != 'pull_request'
    #   run: |
    #     docker pull ${{ inputs.uhub_slug }}:${{ steps.meta.outputs.version }}
    #     docker image inspect ${{ inputs.uhub_slug }}:${{ steps.meta.outputs.version }}
    #     docker pull ${{ inputs.ghcr_slug }}:${{ steps.meta.outputs.version }}
    #     docker image inspect ${{ inputs.ghcr_slug }}:${{ steps.meta.outputs.version }}
