name: Release

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      artifact_name:
        description: 'Artifact to download and unpack before building image'
        required: false
        type: string
      changelog_filename:
        required: true
        type: string
      bin_filename:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Prepare release
      env:
        CURRENT_TAG: ${{ inputs.tag }}
      run: |
        docker run -v "$PWD":/workdir quay.io/git-chglog/git-chglog $CURRENT_TAG > ${{ inputs.changelog_filename }}
        cat ${{ inputs.changelog_filename }}
    
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      if: ${{ inputs.artifact_name }}
      with:
        name: ${{ inputs.artifact_name }}
    
    - name: Unzip artifact
      if: ${{ inputs.artifact_name }}
      run: tar -xvf artifact.tar
    
    - name: Release
      uses: softprops/action-gh-release@v0.1.12
      with:
        body_path: ${{ inputs.changelog_filename }}
        files: ${{ inputs.bin_filename }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
